In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from datetime import datetime
import matplotlib.dates as mdates
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
import matplotlib.ticker as mtick
import os
import platform
import glob

In [10]:
import getpass

# Obtener el nombre de usuario actual
user = getpass.getuser()

if platform.system() == 'Darwin':
    
    if user == 'juliandiazparra':  # Usuario en el primer Mac
        os.chdir(
            '/Users/juliandiazparra/Library/CloudStorage/GoogleDrive-julian.adiaz@hotmail.com/Mi unidad/Negocios/Familiar/GIGANAV')
        
    elif user == 'usuarioo':  # Nombre del usuario en el segundo Mac
        os.chdir(
            '/Users/usuarioo/Library/CloudStorage/GoogleDrive-julian.adiaz@hotmail.com/Mi unidad/Negocios/Familiar/GIGANAV')

# Definir las rutas como antes
folder = os.getcwd()
data = os.path.join(folder, 'Datos')
provisiones = os.path.join(data, 'Provisiones')
facturas = os.path.join(data, 'Facturas')
tickets = os.path.join(data, 'Tickets')
usuarios = os.path.join(data, 'Usuarios')
egresos = os.path.join(data, 'Egresos')
transacciones = os.path.join(data, 'Transacciones')
analisis = os.path.join(folder, 'Operacion/Analisis')
resultados = os.path.join(analisis, 'Resultados')
bases = os.path.join(analisis, 'Bases_analisis')
outputs = os.path.join(analisis, 'Outputs')
plots = os.path.join(outputs, 'Gráficos')
usuarios_clean = os.path.join(bases, 'Usuarios')
transac_clean = os.path.join(bases, 'Transacciones')
tickets_clean = os.path.join(bases, 'Tickets')
facturas_clean = os.path.join(bases, 'Facturas')
egresos_clean = os.path.join(bases, 'Egresos')
working = os.path.join(bases, 'Bases_trabajo')
codigo = os.path.join(folder, 'Operacion/Analisis/Código')
conciliaciones = os.path.join(folder, 'Operacion/Operativo/Administrativo/Conciliaciones')

## Importación base de trabajo

In [11]:
list_of_files = glob.glob(os.path.join(outputs,'Base_tickets*.csv'))
latest_file = max(list_of_files, key=os.path.getctime)
working_data=pd.read_csv(latest_file, low_memory=False)
working_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16876 entries, 0 to 16875
Data columns (total 60 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_ticket              16876 non-null  int64
 1   nombre                 16876 non-null  object
 2   asunto                 16876 non-null  object
 3   tecnico                16876 non-null  object
 4   zona                   16832 non-null  object
 5   abierto_por            16876 non-null  object
 6   departamento           16876 non-null  object
 7   categoria              16758 non-null  object
 8   subcategoria           5567 non-null   object
 9   fecha_abierto          16876 non-null  object
 10  fecha_visita           16850 non-null  object
 11  fecha_cerrado          16876 non-null  object
 12  mes_crd                16876 non-null  object
 13  first_day              16876 non-null  object
 14  tiempo_resolucion      16876 non-null  object
 15  tiempo_asignacion      16850 non-null  object
 16  tiempo_atencion        16850 non-null  object
 17  Id                     16803 non-null  float64
 18  estado                 16803 non-null  object
 19  radio                  16803 non-null  float64
 20  Tipo estrato           16803 non-null  float64
 21  megas                  12043 non-null  float64
 22  TV                     16803 non-null  float64
 23  Telefono               12765 non-null  object
 24  Movil                  16710 non-null  object
 25  Correo                 12979 non-null  object
 26  Zona                   16759 non-null  object
 27  tarifa                 16803 non-null  float64
 28  meses_suspendido       16803 non-null  float64
 29  deuda                  16803 non-null  float64
 30  ID de registro         16730 non-null  float64
 31  tecnologia             16803 non-null  object
 32  tipo_servicio          16803 non-null  object
 33  tipo_usuario           16803 non-null  object
 34  _merge                 16876 non-null  object
 35  tecnico_1              2153 non-null   object
 36  tecnico_2              402 non-null    object
 37  conector_mecanico      2153 non-null   float64
 38  fibra_drop             2153 non-null   float64
 39  conector_coaxial       2153 non-null   float64
 40  tensores               2153 non-null   float64
 41  cable_coaxial          2153 non-null   float64
 42  cable_utp              2153 non-null   float64
 43  rjs                    2153 non-null   float64
 44  deco_tdt               2153 non-null   float64
 45  splitter_2             2153 non-null   float64
 46  splitter_3             2153 non-null   float64
 47  splitter_4             2153 non-null   float64
 48  mininodos              2153 non-null   float64
 49  otros                  2153 non-null   float64
 50  merge2                 16876 non-null  object
 51  fecha_enc_sat          177 non-null    object
 52  calificacion_personal  177 non-null    float64
 53  resolvio               177 non-null    float64
 54  promoter               177 non-null    float64
 55  calificacion_servicio  148 non-null    float64
 56  merge_sat              16876 non-null  object
 57  encuesta               16876 non-null  bool
 58  residencial            16876 non-null  int64
 59  tiempo_resol           16876 non-null  float64
dtypes: bool(1), float64(27), int64(2), object(30)
memory usage: 7.6+ MB

In [12]:
mask_tecnico=working_data['categoria'].isin(['instal','soporte','retiro','traslado','mantenimiento'])
working_data.loc[mask_tecnico]

,id_ticket,nombre,asunto,tecnico,zona,abierto_por,departamento,categoria,subcategoria,fecha_abierto,...,merge2,fecha_enc_sat,calificacion_personal,resolvio,promoter,calificacion_servicio,merge_sat,encuesta,residencial,tiempo_resol
3,25595,ALFA LISETH PARDO LOZANO,soporte sin servicio de tv,ALFONSO ARANGO TORO,VEREDA MONTERREY,KGUERRERO,tecnico,soporte,sin_servicio,2024-10-22 16:01:44,...,both,NaN,NaN,NaN,NaN,NaN,left_only,True,1,0.711146
7,25586,PAULA ANDREA REYES BAUTISTA,soporte sin servicio,ESNEIDER GARCIA BARAJAS,EL OASIS,KGUERRERO,tecnico,soporte,sin_servicio,2024-10-22 11:58:15,...,both,NaN,NaN,NaN,NaN,NaN,left_only,True,1,0.891227
13,25573,LUZ MARIA AGUIRRE ZULUAGA,soporte sin servicio,ESNEIDER GARCIA BARAJAS,CGTO LA PEDREGOSA,KGUERRERO,tecnico,soporte,sin_servicio,2024-10-22 08:17:47,...,both,NaN,NaN,NaN,NaN,NaN,left_only,True,1,0.111933
14,25572,KELLY JOHANNA PINO CHOGO,soporte sin servicio,LEONARDO QUEZADA RAMIREZ,ALTOS DEL PROGRESO,KGUERRERO,tecnico,soporte,sin_servicio,2024-10-22 08:13:50,...,left_only,NaN,NaN,NaN,NaN,NaN,left_only,False,1,0.975764
16,25570,JAMEL ENRIQUE PUELLO,instalacion internet + tv,ALFONSO ARANGO TORO,EL OASIS,KGUERRERO,tecnico,instal,NaN,2024-10-21 17:36:37,...,both,NaN,NaN,NaN,NaN,NaN,left_only,True,1,0.976748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16869,7228,RAFAEL RODRIGUEZ ROJAS,retirar servicio,JAIME LEONARDO BARRERA BARAJAS,SAN RAFAEL,DREHINNYLOZANO,tecnico,retiro,NaN,2021-09-20 08:28:33,...,left_only,NaN,NaN,NaN,NaN,NaN,left_only,False,0,233.116644
16870,7228,RAFAEL RODRIGUEZ ROJAS,retirar servicio,JAIME LEONARDO BARRERA BARAJAS,SAN RAFAEL,DREHINNYLOZANO,tecnico,retiro,NaN,2021-09-20 08:28:33,...,left_only,NaN,NaN,NaN,NaN,NaN,left_only,False,0,233.116644
16871,7209,EDILMARIS TORREJANO DAVILA,retirar servicio,No asignado,ALTOS DEL PROGRESO,ASESOR,tecnico,retiro,NaN,2021-09-17 15:36:00,...,left_only,NaN,NaN,NaN,NaN,NaN,left_only,False,1,237.929039
16873,6154,YENNYFER RIVERA RODRIGUEZ,retiro de servicio,No asignado,BETANCURT,EDGARDFONSECA,tecnico,retiro,NaN,2021-07-31 08:16:18,...,left_only,NaN,NaN,NaN,NaN,NaN,left_only,False,1,284.124572
16875,5879,ROSA ANGELICA SUAREZ MEJIA,instalar tv,JAIME LEONARDO BARRERA BARAJAS,1º DE ABRIL,ASESOR,tecnico,instal,NaN,2021-07-15 15:34:33,...,left_only,NaN,NaN,NaN,NaN,NaN,left_only,False,1,405.976204

In [14]:
#Analisis categoria solicitud tipo de cliente
working_data.loc[mask_tecnico].groupby(
    ['mes_crd','tipo_servicio','categoria']).agg(
    num_tickets=('id_ticket','nunique'), 
    tiempo_respuesta=('tiempo_resol',pd.Series.median)
).reset_index()

     mes_crd tipo_servicio categoria  num_tickets  tiempo_respuesta
0    2022-01   corporativo    instal            2          0.010098
1    2022-01   corporativo    retiro            3          1.858322
2    2022-01   corporativo   soporte           12          0.099826
3    2022-01   residencial    instal           70          0.634803
4    2022-01   residencial    retiro           68          0.002708
..       ...           ...       ...          ...               ...
241  2024-10   corporativo   soporte            8          1.623194
242  2024-10   residencial    instal           53          3.792813
243  2024-10   residencial    retiro           26          3.796181
244  2024-10   residencial   soporte          270          3.965451
245  2024-10   residencial  traslado           29          2.932546

[246 rows x 5 columns]

In [15]:
#analisis residencia/empresa
summary_res_emp=working_data.loc[mask_tecnico].groupby(
    ['mes_crd','tipo_servicio','categoria']).agg(
    num_tickets=('id_ticket','nunique'), 
    tiempo_respuesta=('tiempo_resol',pd.Series.mean)).reset_index().pivot(
    index='mes_crd',columns=[
        'categoria','tipo_servicio'], 
    values=['num_tickets',
           'tiempo_respuesta']).reset_index()
summary_res_emp.tail()

               mes_crd num_tickets                                      \
categoria                   instal      retiro     soporte      instal
tipo_servicio          corporativo corporativo corporativo residencial
29             2024-06         3.0         3.0         7.0       188.0
30             2024-07         5.0         3.0         7.0       187.0
31             2024-08         3.0         NaN        10.0        71.0
32             2024-09         1.0         3.0        15.0        87.0
33             2024-10         1.0         2.0         8.0        53.0

                                                                             \
categoria          retiro     soporte    traslado             mantenimiento
tipo_servicio residencial residencial residencial corporativo   residencial
29                   33.0       166.0        23.0         2.0           1.0
30                   48.0       202.0        28.0         NaN           NaN
31                   44.0       326.0        25.0         NaN           NaN
32                   49.0       549.0        28.0         1.0           NaN
33                   26.0       270.0        29.0         NaN           NaN

              tiempo_respuesta                                      \
categoria               instal      retiro     soporte      instal
tipo_servicio      corporativo corporativo corporativo residencial
29                    3.017238    6.009931    3.333712    4.368369
30                    4.163579   27.975448    2.813404    5.316559
31                    3.622431         NaN    0.824973    2.915619
32                    1.627546    2.139078    2.209593    1.895643
33                    1.337442    2.079763    2.352979    5.046540


categoria          retiro     soporte    traslado             mantenimiento
tipo_servicio residencial residencial residencial corporativo   residencial
29               6.160829    5.043271    4.599576    3.759155      3.482025
30               6.022392    6.087358    6.213743         NaN           NaN
31               4.567179    2.777217    3.334915         NaN           NaN
32               3.420593    2.724489    2.897211   23.384861           NaN
33               5.831648    4.920633    3.030354         NaN           NaN

In [16]:
#Analisis TV o internet
summary_int_tv=working_data.loc[mask_tecnico].groupby(
    ['mes_crd','tipo_usuario','categoria']).agg(
    num_tickets=('id_ticket','nunique'), 
    tiempo_respuesta=('tiempo_resol',pd.Series.mean)).reset_index().pivot(
    index='mes_crd',columns=[
        'categoria','tipo_usuario'], 
    values=['num_tickets',
           'tiempo_respuesta']).reset_index()
summary_int_tv.tail(10)

              mes_crd num_tickets                                             \
categoria                  instal   retiro  soporte traslado  instal  retiro
tipo_usuario             internet internet internet internet paquete paquete
24            2024-01        53.0     42.0     80.0     16.0    39.0     2.0
25            2024-02        43.0     51.0    112.0     17.0    43.0     8.0
26            2024-03        28.0     62.0     65.0     23.0    64.0    10.0
27            2024-04        48.0     60.0     60.0     19.0    39.0     3.0
28            2024-05        32.0     41.0     63.0      8.0    40.0     7.0
29            2024-06        52.0     31.0     71.0     13.0   139.0     5.0
30            2024-07        60.0     46.0     75.0     14.0   133.0     4.0
31            2024-08        29.0     42.0    119.0      7.0    44.0     2.0
32            2024-09        29.0     46.0    122.0     11.0    59.0     6.0
33            2024-10        23.0     21.0     72.0     10.0    31.0     6.0

                                            tiempo_respuesta            \
categoria    soporte traslado mantenimiento           instal    retiro
tipo_usuario paquete  paquete      internet         internet  internet
24             115.0     22.0           NaN         2.199164  3.102720
25             193.0     14.0           NaN         2.600787  4.147053
26              98.0      4.0           NaN         3.324241  4.759682
27             129.0     22.0           1.0         8.804784  5.775294
28              97.0     10.0           1.0         4.204521  6.659369
29             103.0     12.0           1.0         5.962647  6.498774
30             135.0     14.0           NaN         4.690414  7.702631
31             219.0     18.0           NaN         2.611742  4.471492
32             445.0     18.0           NaN         1.773497  3.606926
33             207.0     19.0           NaN         3.652392  4.712985

                                                                          \
categoria      soporte  traslado    instal    retiro   soporte  traslado
tipo_usuario  internet  internet   paquete   paquete   paquete   paquete
24            4.572006  3.334146  2.951899  1.971181  4.113530  3.575816
25            8.848885  4.396856  3.147937  0.863715  7.711751  4.453139
26            2.383222  3.136230  3.321627  2.352562  2.982189  3.790347
27            5.802143  6.914749  3.709405  1.896613  4.335635  3.738978
28            6.339223  6.692903  5.107917  2.068122  6.174610  3.641076
29            5.207670  4.459099  3.729102  3.975035  4.810954  4.611689
30            5.690422  6.183427  5.572392  2.744378  6.152819  6.244059
31            3.042864  4.294446  3.159896  6.624439  2.539957  2.961764
32            3.611284  4.831646  1.948451  1.227060  2.457456  2.855572
33            5.426995  3.229536  5.976241  8.682787  4.648971  2.925521


categoria    mantenimiento
tipo_usuario      internet
24                     NaN
25                     NaN
26                     NaN
27                4.029363
28                0.002546
29                3.482025
30                     NaN
31                     NaN
32                     NaN
33                     NaN

In [17]:
#Analisis fibra/radio
summary_fibra_radio=working_data.loc[
    mask_tecnico].groupby(
    ['mes_crd', 'categoria', 'tecnologia']).agg(
    tiempo_respuesta=('tiempo_resol',pd.Series.mean), 
    num_tickets=('id_ticket', 'nunique'), 
    encuestas=('encuesta', 'sum')).reset_index().pivot(
    index='mes_crd', columns=[
        'categoria', 'tecnologia'], values=[
        'tiempo_respuesta', 'num_tickets', 'encuestas'
    ]).reset_index()

summary_fibra_radio.tail()

            mes_crd tiempo_respuesta                                 \
categoria                     instal               retiro   soporte
tecnologia                     fibra      radio     fibra     fibra
29          2024-06         4.075759  59.129560  6.148255  5.075076
30          2024-07         5.288438        NaN  7.313748  5.992529
31          2024-08         3.064443   0.001049  4.567179  2.577723
32          2024-09         1.913715   0.001065  3.197943  2.592802
33          2024-10         4.980306        NaN  5.563657  4.585143

                                                                     ...  \
categoria              traslado                retiro mantenimiento  ...
tecnologia      radio     fibra      radio      radio         fibra  ...
29           2.110561  4.532342        NaN        NaN      3.482025  ...
30           5.711474  5.637466  22.925775        NaN           NaN  ...
31           6.339572  3.334915        NaN        NaN           NaN  ...
32           7.894206  3.580132        NaN  11.821771           NaN  ...
33          15.980898  3.030354        NaN        NaN           NaN  ...

             num_tickets encuestas                                            \
categoria  mantenimiento    instal       retiro soporte       traslado
tecnologia         fibra     fibra radio  fibra   fibra radio    fibra radio
29                   1.0     177.0   0.0    5.0    80.0   0.0     23.0   NaN
30                   NaN     146.0   NaN    1.0    25.0   1.0     13.0   0.0
31                   NaN      32.0   0.0    6.0   157.0   0.0     13.0   NaN
32                   NaN      72.0   0.0   15.0   282.0   6.0     21.0   NaN
33                   NaN      50.0   NaN   20.0   266.0   5.0     26.0   NaN


categoria  retiro mantenimiento
tecnologia  radio         fibra
29            NaN           0.0
30            NaN           NaN
31            NaN           NaN
32            0.0           NaN
33            NaN           NaN

[5 rows x 28 columns]

In [19]:
summary_encuesta_cat=working_data.loc[
    mask_tecnico
].groupby([
    'mes_crd','categoria'
]).agg(num_tickets=(
    'id_ticket','nunique'), 
       encuesta=(
           'encuesta','sum')).reset_index().pivot(
    columns='categoria',
    index='mes_crd',values=[
        'num_tickets',
        'encuesta']).reset_index()

for i in ['instal','retiro','soporte','traslado']:
    summary_encuesta_cat.loc[
        :,'per_enc_'+i]=summary_encuesta_cat[
        ('encuesta',i)]/summary_encuesta_cat[
        ('num_tickets',i)]
summary_encuesta_cat=summary_encuesta_cat.iloc[:,np.r_[0,-4:0]]

nombre_columnas=[]
for i, x in enumerate(list(summary_encuesta_cat.columns)):
    nombre_columnas.append(x[0])

summary_encuesta_cat.columns=nombre_columnas
summary_encuesta_cat.tail()

    mes_crd  per_enc_instal  per_enc_retiro  per_enc_soporte  per_enc_traslado
29  2024-06        0.927083        0.138889         0.462428          0.958333
30  2024-07        0.772487        0.020000         0.126214          0.464286
31  2024-08        0.438356        0.136364         0.471471          0.520000
32  2024-09        0.818182        0.288462         0.516014          0.724138
33  2024-10        0.916667        0.740741         0.978571          0.896552

In [20]:
for i in [summary_int_tv,summary_fibra_radio,summary_res_emp,]:
    nombres_columnas=[]
    for k, x  in enumerate(list(i.columns)):            
        nombres_columnas.append('_'.join([str(j) for j in list(x)]))
    i.columns=nombres_columnas
    i.rename(columns={'mes_crd__':'mes_crd'}, inplace=True)

In [21]:
working_summary=summary_fibra_radio.merge(
    summary_int_tv, on='mes_crd',how='inner').merge(
    summary_res_emp, on='mes_crd',how='inner').merge(
    summary_encuesta_cat, on='mes_crd',how='inner')
working_summary.tail()

,mes_crd,tiempo_respuesta_instal_fibra,tiempo_respuesta_instal_radio,tiempo_respuesta_retiro_fibra,tiempo_respuesta_soporte_fibra,tiempo_respuesta_soporte_radio,tiempo_respuesta_traslado_fibra,tiempo_respuesta_traslado_radio,tiempo_respuesta_retiro_radio,tiempo_respuesta_mantenimiento_fibra,...,tiempo_respuesta_instal_residencial,tiempo_respuesta_retiro_residencial,tiempo_respuesta_soporte_residencial,tiempo_respuesta_traslado_residencial,tiempo_respuesta_traslado_corporativo,tiempo_respuesta_mantenimiento_residencial,per_enc_instal,per_enc_retiro,per_enc_soporte,per_enc_traslado
29,2024-06,4.075759,59.129560,6.148255,5.075076,2.110561,4.532342,NaN,NaN,3.482025,...,4.368369,6.160829,5.043271,4.599576,3.759155,3.482025,0.927083,0.138889,0.462428,0.958333
30,2024-07,5.288438,NaN,7.313748,5.992529,5.711474,5.637466,22.925775,NaN,NaN,...,5.316559,6.022392,6.087358,6.213743,NaN,NaN,0.772487,0.020000,0.126214,0.464286
31,2024-08,3.064443,0.001049,4.567179,2.577723,6.339572,3.334915,NaN,NaN,NaN,...,2.915619,4.567179,2.777217,3.334915,NaN,NaN,0.438356,0.136364,0.471471,0.520000
32,2024-09,1.913715,0.001065,3.197943,2.592802,7.894206,3.580132,NaN,11.821771,NaN,...,1.895643,3.420593,2.724489,2.897211,23.384861,NaN,0.818182,0.288462,0.516014,0.724138
33,2024-10,4.980306,NaN,5.563657,4.585143,15.980898,3.030354,NaN,NaN,NaN,...,5.046540,5.831648,4.920633,3.030354,NaN,NaN,0.916667,0.740741,0.978571,0.896552

In [22]:
filepath=os.path.join(outputs,'Resumen_mes_categorias_tecnicas')
working_summary.to_csv(filepath+'.csv')